# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\TR-DM-004\Documents\Programing\Python\Modbus_Client\modbus.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(497, 313)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtIpv1 = QtWidgets.QTextEdit(self.centralwidget)
        self.txtIpv1.setGeometry(QtCore.QRect(70, 70, 61, 31))
        self.txtIpv1.setObjectName("txtIpv1")
        self.txtIpv2 = QtWidgets.QTextEdit(self.centralwidget)
        self.txtIpv2.setGeometry(QtCore.QRect(140, 70, 61, 31))
        self.txtIpv2.setObjectName("txtIpv2")
        self.txtIpv4 = QtWidgets.QTextEdit(self.centralwidget)
        self.txtIpv4.setGeometry(QtCore.QRect(280, 70, 61, 31))
        self.txtIpv4.setObjectName("txtIpv4")
        self.txtIpv3 = QtWidgets.QTextEdit(self.centralwidget)
        self.txtIpv3.setGeometry(QtCore.QRect(210, 70, 61, 31))
        self.txtIpv3.setObjectName("txtIpv3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 40, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnConnect = QtWidgets.QPushButton(self.centralwidget)
        self.btnConnect.setGeometry(QtCore.QRect(350, 70, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnConnect.setFont(font)
        self.btnConnect.setObjectName("btnConnect")
        self.comRead = QtWidgets.QComboBox(self.centralwidget)
        self.comRead.setGeometry(QtCore.QRect(110, 140, 81, 31))
        self.comRead.setObjectName("comRead")
        self.txtRead = QtWidgets.QTextEdit(self.centralwidget)
        self.txtRead.setGeometry(QtCore.QRect(220, 140, 81, 31))
        self.txtRead.setObjectName("txtRead")
        self.btnRead = QtWidgets.QPushButton(self.centralwidget)
        self.btnRead.setGeometry(QtCore.QRect(330, 140, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnRead.setFont(font)
        self.btnRead.setObjectName("btnRead")
        self.btnWrite = QtWidgets.QPushButton(self.centralwidget)
        self.btnWrite.setGeometry(QtCore.QRect(330, 210, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btnWrite.setFont(font)
        self.btnWrite.setObjectName("btnWrite")
        self.txtWrite = QtWidgets.QTextEdit(self.centralwidget)
        self.txtWrite.setGeometry(QtCore.QRect(220, 210, 81, 31))
        self.txtWrite.setObjectName("txtWrite")
        self.comWrite = QtWidgets.QComboBox(self.centralwidget)
        self.comWrite.setGeometry(QtCore.QRect(110, 210, 81, 31))
        self.comWrite.setObjectName("comWrite")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 497, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Ip Adresi"))
        self.btnConnect.setText(_translate("MainWindow", "Bağlan"))
        self.btnRead.setText(_translate("MainWindow", "Veri Oku"))
        self.btnWrite.setText(_translate("MainWindow", "Veri Yaz"))
